spring:
  mongodb:
    uri: mongodb+srv://regussm:pA3a0RCt2RI5cewM@emexo.en2dxtv.mongodb.net
    database: bankingmanagement
  datasource:
    username: postgres
    password: IndiaUSA123
    url: jdbc:postgresql://localhost:5432/transactionorders
