spring:
  mongodb:
    uri: mongodb://admin:StrongPassword123@localhost:27017/?authSource=admin
    database: transactionorders
  datasource:
    username: postgres
    password: IndiaUSA123
    url: jdbc:postgresql://localhost:5432/transactionorders
